# Generated by Django 3.1.7 on 2021-12-22 16:01

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditoPersonas',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('plazo', models.PositiveIntegerField(blank=True, null=True)),
                ('aceptaTerminos', models.SmallIntegerField(default=1)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(max_length=255)),
                ('empresaComercial_id', models.CharField(max_length=255)),
                ('empresaIfis_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
