# Generated by Django 3.1.7 on 2022-02-09 21:30

import apps.CORP.corp_creditoPersonas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp_creditoPersonas', '0002_creditopersonas_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditopersonas',
            name='buroValido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creditopersonas',
            name='calificacionBuro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creditopersonas',
            name='identificacion',
            field=models.FileField(blank=True, null=True, upload_to=apps.CORP.corp_creditoPersonas.models.upload_path),
        ),
        migrations.AddField(
            model_name='creditopersonas',
            name='panillaIESS',
            field=models.FileField(blank=True, null=True, upload_to=apps.CORP.corp_creditoPersonas.models.upload_path),
        ),
        migrations.AddField(
            model_name='creditopersonas',
            name='reporteBuro',
            field=models.FileField(blank=True, null=True, upload_to=apps.CORP.corp_creditoPersonas.models.upload_path),
        ),
        migrations.AddField(
            model_name='creditopersonas',
            name='rolesPago',
            field=models.FileField(blank=True, null=True, upload_to=apps.CORP.corp_creditoPersonas.models.upload_path),
        ),
        migrations.AddField(
            model_name='creditopersonas',
            name='ruc',
            field=models.FileField(blank=True, null=True, upload_to=apps.CORP.corp_creditoPersonas.models.upload_path),
        ),
    ]
