# Generated by Django 3.1.7 on 2022-02-11 16:18

import apps.CORP.corp_creditoPersonas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp_creditoPersonas', '0004_auto_20220211_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditopersonas',
            name='documentoAprobacion',
            field=models.FileField(blank=True, null=True, upload_to=apps.CORP.corp_creditoPersonas.models.upload_path),
        ),
        migrations.AddField(
            model_name='creditopersonas',
            name='fechaAprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
