# Generated by Django 3.1.7 on 2022-02-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp_creditoPersonas', '0005_auto_20220211_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditopersonas',
            name='canal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
