# Generated by Django 3.1.7 on 2022-03-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp_creditoPersonas', '0006_creditopersonas_canal'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditopersonas',
            name='empresasAplican',
            field=models.TextField(blank=True, null=True),
        ),
    ]
