# Generated by Django 3.1.7 on 2022-03-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp_creditoPersonas', '0007_creditopersonas_empresasaplican'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditopersonas',
            name='apellidos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creditopersonas',
            name='interes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditopersonas',
            name='nombres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creditopersonas',
            name='nombresCompleto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creditopersonas',
            name='vigencia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
