# Generated by Django 3.1.7 on 2022-03-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp_creditoPersonas', '0009_creditopersonas_fechaaprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditopersonas',
            name='numeroIdentificacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
