# Generated by Django 3.1.7 on 2022-03-18 20:20

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('corp_creditoPersonas', '0010_creditopersonas_numeroidentificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorizacionCredito',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=200)),
                ('credito', models.CharField(max_length=250)),
                ('entidad', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
