# Generated by Django 3.1.7 on 2021-09-22 17:22

import apps.CENTRAL.central_publicaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=apps.CENTRAL.central_publicaciones.models.upload_path),
        ),
    ]
