# Generated by Django 3.1.7 on 2021-09-27 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('central_publicaciones', '0002_auto_20210922_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompartirPublicaciones',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_publicaciones.publicaciones')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
