# Generated by Django 3.1.7 on 2021-12-28 17:50

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corp_empresas', '0002_auto_20211210_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditoPreaprobados',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('fechaAprobado', models.DateField(blank=True, null=True)),
                ('vigencia', models.DateField(blank=True, null=True)),
                ('concepto', models.CharField(blank=True, max_length=255, null=True)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('plazo', models.SmallIntegerField(blank=True, null=True)),
                ('interes', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, default='Pre aprobado', max_length=255, null=True)),
                ('tipoPersona', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='corp_empresas.empresas')),
            ],
        ),
    ]
