# Generated by Django 3.1.7 on 2021-12-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp_creditoPreaprobados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditopreaprobados',
            old_name='empresa',
            new_name='empresa_financiera',
        ),
        migrations.AddField(
            model_name='creditopreaprobados',
            name='empresa_comercial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creditopreaprobados',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
