# Generated by Django 3.1.7 on 2022-01-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp_creditoPreaprobados', '0002_auto_20211229_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditopreaprobados',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditopreaprobados',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
