# Generated by Django 3.1.7 on 2022-01-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp_creditoPreaprobados', '0003_auto_20220107_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditopreaprobados',
            name='tipoCredito',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creditopreaprobados',
            name='tomarSolicitud',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
