# Generated by Django 3.1.7 on 2022-03-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp_creditoPreaprobados', '0004_auto_20220113_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditopreaprobados',
            name='empresasAplican',
            field=models.TextField(blank=True, null=True),
        ),
    ]
