# Generated by Django 3.1.7 on 2022-02-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_catalogo', '0002_catalogo_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='maximo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='minimo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
