# Generated by Django 3.1.7 on 2021-09-15 15:27

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=150, null=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.CharField(max_length=250, null=True)),
                ('config', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
