# Generated by Django 3.1.7 on 2021-12-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_roles', '0004_roles_tipousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='config',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
