# Generated by Django 3.1.7 on 2021-12-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_roles', '0005_auto_20211208_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='codigo',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='roles',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
