# Generated by Django 3.1.7 on 2021-12-28 20:27

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('corp_empresas', '0002_auto_20211210_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresasConvenio',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('empresa', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corp_empresas.empresas')),
            ],
        ),
    ]
