# Generated by Django 3.1.7 on 2022-01-11 15:20

import apps.CORP.corp_empresas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp_empresas', '0003_empresasconvenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=apps.CORP.corp_empresas.models.upload_path),
        ),
    ]
