# Generated by Django 3.1.7 on 2021-10-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='vigencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='tipo',
            field=models.CharField(default='presentacion', max_length=255),
        ),
    ]
