# Generated by Django 3.1.7 on 2022-01-07 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corp_empresas', '0003_empresasconvenio'),
        ('corp_creditoPreaprobados', '0003_auto_20220107_1432'),
        ('corp_notasPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturasencabezados',
            name='credito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='corp_creditoPreaprobados.creditopreaprobados'),
        ),
        migrations.AddField(
            model_name='facturasencabezados',
            name='empresaComercial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='corp_empresas.empresas'),
        ),
    ]
