# Generated by Django 3.1.7 on 2021-09-23 16:40

import apps.CENTRAL.central_facturas.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('numeroFactura', models.CharField(max_length=200)),
                ('razonSocial', models.TextField(max_length=200)),
                ('provincia', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaEmision', models.DateField()),
                ('importeTotal', models.FloatField()),
                ('categoria', models.CharField(blank=True, max_length=200, null=True)),
                ('urlFoto', models.FileField(blank=True, null=True, upload_to=apps.CENTRAL.central_facturas.models.upload_path)),
                ('urlArchivo', models.FileField(blank=True, null=True, upload_to=apps.CENTRAL.central_facturas.models.upload_path2)),
                ('estado', models.CharField(blank=True, default='Sin calificar', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CalificarCompras',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('atencion', models.CharField(blank=True, max_length=255, null=True)),
                ('calificacion', models.SmallIntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='calificaciones', to='central_facturas.facturas')),
            ],
        ),
    ]
