# Generated by Django 3.1.7 on 2022-01-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_facturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
