# Generated by Django 3.1.7 on 2021-09-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='roles',
        ),
    ]
