# Generated by Django 3.1.7 on 2021-11-25 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central_tipoUsuarios', '0001_initial'),
        ('central_usuarios', '0002_remove_usuarios_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='tipoUsuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='central_tipoUsuarios.tipousuario'),
        ),
    ]
