# Generated by Django 3.1.7 on 2021-12-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_usuarios', '0003_usuarios_tipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
