# Generated by Django 3.1.7 on 2021-12-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_usuarios', '0004_usuarios_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='empresa',
            new_name='empresa_id',
        ),
    ]
