# Generated by Django 3.1.7 on 2021-12-07 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_usuarios', '0005_auto_20211207_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='empresa_id',
        ),
    ]
