# Generated by Django 3.1.7 on 2021-11-28 00:55

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corp_cobrarSupermonedas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizaciones',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('codigoAutorizacion', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('cobrar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='corp_cobrarSupermonedas.cobrarsupermonedas')),
            ],
        ),
    ]
