# Generated by Django 3.1.7 on 2021-12-22 16:03

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RucPersonas',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('identificacion', models.CharField(blank=True, max_length=10, null=True)),
                ('ruc', models.CharField(blank=True, max_length=13, null=True)),
                ('nombreComercial', models.CharField(blank=True, max_length=255, null=True)),
                ('razonSocial', models.CharField(blank=True, max_length=255, null=True)),
                ('pais', models.CharField(blank=True, max_length=255, null=True)),
                ('provincia', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=255, null=True)),
                ('antiguedadRuc', models.SmallIntegerField(blank=True, null=True)),
                ('actividadComercial', models.CharField(blank=True, max_length=255, null=True)),
                ('ventaMensual', models.FloatField(blank=True, null=True)),
                ('gastoMensual', models.FloatField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
