# Generated by Django 3.1.7 on 2021-09-22 21:33

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas_personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialLaboral',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField(null=True)),
                ('empresa', models.CharField(max_length=200)),
                ('tiempoTrabajo', models.SmallIntegerField(null=True)),
                ('cargoActual', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personas_personas.personas')),
            ],
        ),
    ]
