# Generated by Django 3.1.7 on 2022-02-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas_historialLaboral', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiallaboral',
            name='persona',
        ),
        migrations.AddField(
            model_name='historiallaboral',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historiallaboral',
            name='cargoActual',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiallaboral',
            name='empresa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiallaboral',
            name='estado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiallaboral',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiallaboral',
            name='tiempoTrabajo',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
