# Generated by Django 3.1.7 on 2022-02-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas_historialLaboral', '0002_auto_20220214_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiallaboral',
            name='profesion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
