# Generated by Django 3.1.7 on 2022-03-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreAprobados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCargaArchivo', models.DateField(null=True)),
                ('campania', models.CharField(blank=True, max_length=255, null=True)),
                ('registrosCargados', models.CharField(blank=True, max_length=255, null=True)),
                ('linkArchivo', models.CharField(blank=True, max_length=255, null=True)),
                ('tamanioArchivo', models.CharField(blank=True, max_length=150, null=True)),
                ('usuarioCargo', models.CharField(blank=True, max_length=150, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
