# Generated by Django 3.1.7 on 2022-03-28 16:06

import apps.CORP.corp_creditoArchivos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp_creditoArchivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preaprobados',
            name='empresa_financiera',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='preaprobados',
            name='tipoCredito',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preaprobados',
            name='linkArchivo',
            field=models.FileField(blank=True, null=True, upload_to=apps.CORP.corp_creditoArchivos.models.upload_path),
        ),
        migrations.AlterField(
            model_name='preaprobados',
            name='tamanioArchivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preaprobados',
            name='usuarioCargo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
