# Generated by Django 3.1.7 on 2021-09-15 15:26

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('central_roles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acciones',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('idAccionPadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='central_acciones.acciones')),
            ],
        ),
        migrations.CreateModel(
            name='AccionesPorRol',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=0)),
                ('idAccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_acciones.acciones')),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_roles.roles')),
            ],
        ),
        migrations.CreateModel(
            name='AccionesPermitidas',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('idAccion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='central_acciones.acciones')),
            ],
        ),
    ]
